version: '3.1'
services:
  simswap:
    image: humanseg
    container_name: HumanSeg
    volumes:
      - ./input:/input
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]